### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by cyromaniac** [aa6/minetest_wadsprint#6]
Hey man, love the work you do. I was looking around the Minetest forums, and you said you had some issues recovering some of your Minecraft accounts. if you would consider selling the Minecraft account "z5" to me, I would be able to help you recover it as I am quite knowledgeable when it comes to Minecraft accounts. Please let me know if you're interested. Also, if you have a discord and or somewhere else that we could communicate, that would be amazing.

Also, sorry about opening an issue on one of your projects. But, I was unable to contact any other way. I also attempted to make a comment on one of your last commits, but I wasn't sure if you would see it. That's why I've done this to contact you, so I apologize if this is a inconvenience.

**Comment by aa6** [comment]
Hello. I am absolutely amazed by efforts you put into this but can only recommend you not to waste your time and money on Minecraft and invest it in Minetest instead since you don't need to buy an account to play Minetest. I also believe that selling/buying minecraft accounts is illegal thus I don't want to be involved in any illegal actions. Dead game accounts doesn't really worth it. Long live Minetest!
